### ISSUE TITLE
USB port identification

### ISSUE THREAD

**Issue by yanwang631** [neuralaxy/NeuroStimDuino#3]
Hi, I am a graduate student researching about functional electrical stimulation control strategy, I reproduced NeuroStimDuino according to your information, but after the soldering is done, the computer does not recognize the port when I connect it via usb. We have troubleshoot some problems but still can't succeed, can you help me to analyze the reason?Can you give me a process of using the equipment？

**Comment by neuralaxy** [comment]
Hi @yanwang631 
The USB port is controlled by an FTDI USB-to-serial chip (FT232RL). Have you tried installing FTDI drivers?

**Comment by yanwang631** [comment]
Thank you very much for your answer, now I am facing the problem that when I connect to the computer through usb, the computer does not show any port, I checked the power supply of FT232RL and dsp, it is normal, so now I am very confused and would like to ask you what could be the reason for this
