### ISSUE TITLE
Program compilation and download

### ISSUE THREAD

**Issue by yanwang631** [neuralaxy/NeuroStimDuino#4]
Hi, neuralaxy 
   How to upload the program to the DSP chip？Because I don't have a mega256 or other additional controllers at the moment，can you tell me how to control neurostimduino directly through computer?

**Comment by neuralaxy** [comment]
Hello Yanwang,

Since you have fabricated the board, you will need to upload the firmware
for controlling NeuroStimDuino using USB or an Arduiono. We haven't shared
our firmware yet, pending some final changes and modifications required.
Once, we share the firmware you will have access to it.

Regards,
Neuralaxy LLC

**Comment by yanwang631** [comment]
neuralaxy，Thank you very much for your answer.I know that the firmware is being adjusted and cannot be made public right now. But because my graduate advisor is pushing hard for experiments on electrical stimulation. I use it just to acquire human surface EMG signals in the case of electrical stimulation. It will not be used for commercial or other purposes, so I was wondering if you could please send a version of the firmware first. My email is **694216849@qq.com**. Finally thank you again!

**Comment by yanwang631** [comment]
> Hello Yanwang, Since you have fabricated the board, you will need to upload the firmware for controlling NeuroStimDuino using USB or an Arduiono. We haven't shared our firmware yet, pending some final changes and modifications required. Once, we share the firmware you will have access to it. Regards


neuralaxy，Thank you very much for your answer.I know that the firmware is being adjusted and cannot be made public right now. But because my graduate advisor is pushing hard for experiments on electrical stimulation. I use it just to acquire human surface EMG signals in the case of electrical stimulation. It will not be used for commercial or other purposes, so I was wondering if you could please send a version of the firmware first. My email is 694216849@qq.com. Finally thank you again!

**Comment by neuralaxy** [comment]
Hello @yanwang631 

Sorry for the late response. The .HEX file for dsPIC controller is now available here: https://github.com/neuralaxy/NeuroStimDuino/blob/main/Software/Firmware/NeuroStimDuino.X.production.hex. Instructions for burning the hex file using MPLAB-X are also provided in the comments. 

We will be uploading the source code in a few days as well. Till then you can get started with the HEX file and use it for your project. Hope this is helpful.
